#!/usr/bin/perl

# Generated by /home/ariel/htpl-2.70/htpldbg from wow.htpl on Tue Jun 13 17:19:26 2000
#

use lib '/home/ariel/htpl-2.70', '/home/ariel/htpl-2.70';

# /home/ariel/htpl-2.70/htpl.head follows:
use HTML::HTPL::Lib;
use HTML::HTPL::Sys qw(exit);

&HTML::HTPL::Sys::htpl_startup;

# End of /home/ariel/htpl-2.70/htpl.head
# wow.htpl begins
#line 1 wow.htpl
# End wow.htpl
exit(0);
