/*
 * This file was generated automatically by xsubpp version 1.9507 from the 
 * contents of Calendar.xs. Do not edit this file, edit Calendar.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Calendar.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "hdate.h"

#line 16 "Calendar.c"
XS(XS_Locale__Hebrew__Calendar__j2g)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: Locale::Hebrew::Calendar::_j2g(d, m, y)");
    {
	int	d = (int)SvIV(ST(0));
	int	m = (int)SvIV(ST(1));
	int	y = (int)SvIV(ST(2));
	AV *	RETVAL;
#line 14 "Calendar.xs"
	AV *a;
	struct hdate *g;

	g = gdate(d, m, y);

	a = newAV();
	av_push(a, newSViv(g->hd_day + 1));
	av_push(a, newSViv(g->hd_mon));
	av_push(a, newSViv(g->hd_year));
	RETVAL = a;
#line 38 "Calendar.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Locale__Hebrew__Calendar__g2j)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: Locale::Hebrew::Calendar::_g2j(d, m, y)");
    {
	int	d = (int)SvIV(ST(0));
	int	m = (int)SvIV(ST(1));
	int	y = (int)SvIV(ST(2));
	AV *	RETVAL;
#line 33 "Calendar.xs"
	AV *a;
	struct hdate *g;

	g = hdate(d, m, y);

	a = newAV();
	av_push(a, newSViv(g->hd_day + 1));
	av_push(a, newSViv(g->hd_mon));
	av_push(a, newSViv(g->hd_year));
	RETVAL = a;
#line 66 "Calendar.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Locale__Hebrew__Calendar)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Locale::Hebrew::Calendar::_j2g", XS_Locale__Hebrew__Calendar__j2g, file);
        newXS("Locale::Hebrew::Calendar::_g2j", XS_Locale__Hebrew__Calendar__g2j, file);
    XSRETURN_YES;
}

