/*
 * This file was generated automatically by xsubpp version 1.9507 from the 
 * contents of SQL.xs. Do not edit this file, edit SQL.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "SQL.xs"
#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#ifdef __cplusplus
}
#endif


#line 22 "SQL.c"
#define BUFF_SIZE 8192
#define QUOTE 1
#define INSIDE 2
#define BACK 4
#define THAT 8
#define ADDTOKEN token = newSVpv(str, dst - str); dst = str; av_push(result, token);
#define CONTROL "=<>,() "
#include <string.h>
XS(XS_HTML__HTPL__SQL_tokenize_sql)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: HTML::HTPL::SQL::tokenize_sql(sql)");
    {
	char *	sql = (char *)SvPV(ST(0),PL_na);
	AV *	RETVAL;
#line 28 "SQL.xs"
    AV *result;
    char *ch, *dst;
    char str[BUFF_SIZE];
    int flag = 0;
    SV *token;


    result = newAV();

    ch = sql;
    dst = str;

    while (*ch) {
        if ((strchr(CONTROL, *ch)) && flag != QUOTE) {
            if (flag == THAT) {
                ADDTOKEN
                *dst++ = *ch++;
            }
            flag = 0;
        } else if (*ch == '\'') {
            switch(flag) {
                case QUOTE: flag = 0;
                            break;
                default:    flag = QUOTE;
            }
        } else if (*ch == '\\') flag = BACK;
        else  if (*ch == ':' && flag == 0) {
            flag = THAT;
            ADDTOKEN
        } else if (flag == 0) flag = INSIDE;
        *dst++ = *ch++;
    }

    ADDTOKEN

    RETVAL = result;

#line 77 "SQL.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_HTML__HTPL__SQL)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("HTML::HTPL::SQL::tokenize_sql", XS_HTML__HTPL__SQL_tokenize_sql, file);
    XSRETURN_YES;
}

